# Generated by Django 3.2 on 2023-08-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(1, 'user'), (2, 'moderator'), (3, 'admin')], default=1, max_length=256),
        ),
    ]
